create extension if not exists pg_cron;

create table if not exists public.todo_users (
  id bigint generated by default as identity primary key,
  name text not null,
  deletion_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint todo_users_name_nonblank check (btrim(name) <> ''),
  constraint todo_users_name_length check (char_length(btrim(name)) <= 80)
);

create or replace function public.set_default_todo_user_name()
returns trigger
language plpgsql
as $$
begin
  if coalesce(btrim(new.name), '') = '' then
    new.name := 'USER' || new.id;
  else
    new.name := btrim(new.name);
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists set_default_todo_user_name on public.todo_users;
create trigger set_default_todo_user_name
before insert or update of name on public.todo_users
for each row execute function public.set_default_todo_user_name();

create table if not exists public.todo_lists (
  id text primary key,
  user_id bigint not null references public.todo_users(id) on delete cascade,
  name text not null default 'To do',
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, user_id)
);

create table if not exists public.todo_items (
  id text primary key,
  list_id text not null,
  user_id bigint not null references public.todo_users(id) on delete cascade,
  title text not null default '',
  status text not null default 'action' check (status in ('action', 'awaiting', 'done')),
  priority text not null default 'none' check (priority in ('none', 'important', 'urgent', 'urgent_important')),
  created bigint not null,
  updated bigint not null,
  foreign key (list_id, user_id) references public.todo_lists(id, user_id) on delete cascade
);

create index if not exists todo_users_visible_idx on public.todo_users (deletion_at, id);
create index if not exists todo_lists_user_position_idx on public.todo_lists (user_id, position, created_at);
create index if not exists todo_items_list_created_idx on public.todo_items (list_id, created);

alter table public.todo_users enable row level security;
alter table public.todo_lists enable row level security;
alter table public.todo_items enable row level security;

drop policy if exists "Public todo user access" on public.todo_users;
create policy "Public todo user access"
on public.todo_users for all to anon using (true) with check (true);

drop policy if exists "Public todo list access" on public.todo_lists;
create policy "Public todo list access"
on public.todo_lists for all to anon using (true) with check (true);

drop policy if exists "Public todo item access" on public.todo_items;
create policy "Public todo item access"
on public.todo_items for all to anon using (true) with check (true);

create or replace function public.delete_todo_user(target_user_id bigint)
returns table (deleted_now boolean, deletion_at timestamptz)
language plpgsql
as $$
declare
  has_entries boolean;
begin
  select exists (
    select 1 from public.todo_items where user_id = target_user_id
  ) into has_entries;

  if has_entries then
    return query
    update public.todo_users
    set deletion_at = now() + interval '7 days'
    where todo_users.id = target_user_id and todo_users.deletion_at is null
    returning false, todo_users.deletion_at;
  else
    delete from public.todo_users where id = target_user_id;
    return query select true, null::timestamptz;
  end if;
end;
$$;

create or replace function public.replace_todo_workspace(payload jsonb)
returns void
language plpgsql
as $$
begin
  delete from public.todo_users;

  insert into public.todo_users (id, name, deletion_at, created_at, updated_at)
  select id, name, deletion_at, coalesce(created_at, now()), coalesce(updated_at, now())
  from jsonb_to_recordset(payload->'users') as x(
    id bigint, name text, deletion_at timestamptz, created_at timestamptz, updated_at timestamptz
  );

  insert into public.todo_lists (id, user_id, name, position, created_at, updated_at)
  select id, user_id, name, position, coalesce(created_at, now()), coalesce(updated_at, now())
  from jsonb_to_recordset(payload->'lists') as x(
    id text, user_id bigint, name text, position integer, created_at timestamptz, updated_at timestamptz
  );

  insert into public.todo_items (id, list_id, user_id, title, status, priority, created, updated)
  select id, list_id, user_id, title, status, priority, created, updated
  from jsonb_to_recordset(payload->'items') as x(
    id text, list_id text, user_id bigint, title text, status text, priority text, created bigint, updated bigint
  );

  perform setval(
    pg_get_serial_sequence('public.todo_users', 'id'),
    coalesce((select max(id) from public.todo_users), 1),
    exists(select 1 from public.todo_users)
  );
end;
$$;

do $$
declare
  job_id bigint;
begin
  for job_id in select jobid from cron.job where jobname = 'purge-expired-todo-users' loop
    perform cron.unschedule(job_id);
  end loop;
  perform cron.schedule(
    'purge-expired-todo-users',
    '17 3 * * *',
    $cron$delete from public.todo_users where deletion_at is not null and deletion_at <= now()$cron$
  );
exception when undefined_table then
  raise notice 'pg_cron is unavailable; schedule deletion of expired todo users externally.';
end;
$$;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'todo_users'
  ) then
    alter publication supabase_realtime add table public.todo_users;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'todo_lists'
  ) then
    alter publication supabase_realtime add table public.todo_lists;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'todo_items'
  ) then
    alter publication supabase_realtime add table public.todo_items;
  end if;
end $$;
